eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        service-url:
            default-zone: http://localhost:8761/eureka
server:
    port: 8766
spring:
    application:
        name: Zuul-Security
zuul:
    ignoredServices: '*'
    routes:
        Note-Service:
            path: /note/**
            service-id: Note-Service
            strip-prefix: true
        User-Service:
            path: /user/**
            service-id: User-Service
            strip-prefix: true
